name: "AES Ohio Energy Usage"
description: "Logs into AES Ohio (myprofile.aes-ohio.com), downloads your electricity usage, and imports it into Home Assistant's long-term statistics for the Energy Dashboard."
version: "0.2.3"
slug: "ohio_aes"
init: false
arch:
  - aarch64
  - amd64
startup: "services"
boot: "auto"
homeassistant_api: true
options:
  aes_username: ""
  aes_password: ""
  days_back: 3
  run_interval_hours: 12
schema:
  aes_username: str
  aes_password: password
  days_back: int(1,30)
  run_interval_hours: int(1,24)
map:
  - share:rw
logger: true
