name: "Mazda Connected Services"
description: "Local API server for Mazda Connected Services via node-mymazda"
version: "1.2.6"
slug: "mazda-connected"
init: false
arch:
  - aarch64
  - amd64
host_network: true
options:
  email: ""
  password: ""
  region: "MNAO"
  poll_interval_minutes: 5
schema:
  email: str
  password: str
  region: list(MNAO|MME|MJO)
  poll_interval_minutes: int(1,60)
map:
  - config:rw
homeassistant_api: false
ingress: false
panel_icon: mdi:car